 name: Build WASM

 on:
   workflow_dispatch:  # Allows manual trigger
 
   push:
     # branches:
       # - main
     paths:
       - "src/**"
       - "Cargo.toml"
       - "Cargo.lock"
   pull_request:
     branches:
       - main
     paths:
        - "src/**"
        - "Cargo.toml"
        - "Cargo.lock"


 jobs:
   build:
     name: Build WASM Module
     runs-on: ubuntu-latest

     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4

       - name: Set up Rust
         uses: actions-rs/toolchain@v1
         with:
           toolchain: stable
           target: wasm32-unknown-unknown
           override: true
       - name: Install wasm-pack
         run: cargo install wasm-pack

       - name: Build WASM
         run: wasm-pack build --target web --out-dir pkg
       - name: Push
         run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
         
          git add .
          git commit -m "${{ env.FAKE_HASH }}" 
          git push -f
       - name: Upload WASM artifact
         uses: actions/upload-artifact@v4
         with:
           name: wasm-pkg
           path: pkg
